name: Build and Deploy Storybook

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    steps:
      - uses: actions/checkout@v3
      - name: Merge main -> storybook
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: main
          target_branch: storybook
          github_token: ${{ github.token }}
