name: Mirror Storybook Branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror main branch to storybook branch
    steps:
      - name: Mirror action step
        uses: zofrex/mirror-branch@v1
        with:
          target-branch: storybook
